INSERT INTO clubs (id,name,active) VALUES(1,'Bait and Bullet',1);
INSERT INTO clubs (id,name,active) VALUES(2,'Local',1);
INSERT INTO clubs (id,name,active) VALUES(3,'Viva Hardigg Outdoors Club',1);
INSERT INTO clubs (id,name,active) VALUES(4,'Cabin and Trail',1);
INSERT INTO clubs (id,name,active) VALUES(5,'Archery Club',1);
INSERT INTO clubs (id,name,active) VALUES(6,'Alpine Club Ski Team',1);
INSERT INTO clubs (id,name,active) VALUES(7,'Mountain Biking',1);
INSERT INTO clubs (id,name,active) VALUES(8,'Graduate Outing Club',1);
INSERT INTO clubs (id,name,active) VALUES(9,'Winter Sports',1);
INSERT INTO clubs (id,name,active) VALUES(10,'CnT Trailwork',1);
INSERT INTO clubs (id,name,active) VALUES(11,'People of Color Outdoors',1);
INSERT INTO clubs (id,name,active) VALUES(12,'Timber Team',1);
INSERT INTO clubs (id,name,active) VALUES(13,'Surf Club',1);
INSERT INTO clubs (id,name,active) VALUES(14,'Biathlon Club',1);
INSERT INTO clubs (id,name,active) VALUES(15,'Snowboard Club',1);
INSERT INTO clubs (id,name,active) VALUES(16,'Environmental Students of Dartmouth',1);
INSERT INTO clubs (id,name,active) VALUES(17,'Mountaineering',1);
INSERT INTO clubs (id,name,active) VALUES(18,'Nordic Club Ski Team',1);
INSERT INTO clubs (id,name,active) VALUES(19,'Other',1);
INSERT INTO clubs (id,name,active) VALUES(20,'Ledyard',1);
INSERT INTO clubs (id,name,active) VALUES(21,'Climbing Team',1);
INSERT INTO clubs (id,name,active) VALUES(22,'Farm Club',1);
INSERT INTO clubs (id,name,active) VALUES(23,'OPO',1);
INSERT INTO clubs (id,name,active) VALUES(24,'Ski Patrol',1);
INSERT INTO clubs (id,name,active) VALUES(25,'First-Year Trips',1);
INSERT INTO clubs (id,name,active) VALUES(26,'DIJE',1);
INSERT INTO clubs (id,name,active) VALUES(27,'Skate Club',1);
INSERT INTO clubs (id,name,active) VALUES(28,'Flora and Fauna',1);
INSERT INTO clubs (id,name,active) VALUES(29,'DOC',1);
