INSERT INTO clubs VALUES(1,'Bait and Bullet',1);
INSERT INTO clubs VALUES(2,'Local',1);
INSERT INTO clubs VALUES(3,'Viva Hardigg Outdoors Club',1);
INSERT INTO clubs VALUES(4,'Cabin and Trail',1);
INSERT INTO clubs VALUES(5,'Archery Club',1);
INSERT INTO clubs VALUES(6,'Alpine Club Ski Team',1);
INSERT INTO clubs VALUES(7,'Mountain Biking',1);
INSERT INTO clubs VALUES(8,'Graduate Outing Club',1);
INSERT INTO clubs VALUES(9,'Winter Sports',1);
INSERT INTO clubs VALUES(10,'CnT Trailwork',1);
INSERT INTO clubs VALUES(11,'People of Color Outdoors',1);
INSERT INTO clubs VALUES(12,'Timber Team',1);
INSERT INTO clubs VALUES(13,'Surf Club',1);
INSERT INTO clubs VALUES(14,'Biathlon Club',1);
INSERT INTO clubs VALUES(15,'Snowboard Club',1);
INSERT INTO clubs VALUES(16,'Environmental Students of Dartmouth',1);
INSERT INTO clubs VALUES(17,'Mountaineering',1);
INSERT INTO clubs VALUES(18,'Nordic Club Ski Team',1);
INSERT INTO clubs VALUES(19,'Other',1);
INSERT INTO clubs VALUES(20,'Ledyard',1);
INSERT INTO clubs VALUES(21,'Climbing Team',1);
INSERT INTO clubs VALUES(22,'Farm Club',1);
INSERT INTO clubs VALUES(23,'OPO',1);
INSERT INTO clubs VALUES(24,'Ski Patrol',1);
INSERT INTO clubs VALUES(25,'First-Year Trips',1);
INSERT INTO clubs VALUES(26,'DIJE',1);
INSERT INTO clubs VALUES(27,'Skate Club',1);
INSERT INTO clubs VALUES(28,'Flora and Fauna',1);
INSERT INTO clubs VALUES(29,'DOC',1);
